name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (adjust the version as needed)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Compile the Java code
      - name: Compile Java code
        run: mvn compile

  # Check Java code formatting using google-java-format
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4 # v2 minimum required
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install google-java-format
        run: |
          wget https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar -O google-java-format.jar

      - name: Run google-java-format
        run: |
          find . -name "*.java" -exec java -jar google-java-format.jar --replace {} +

      - name: Show formatted changes
        run: git diff --color || echo "No changes needed"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Apply Google Java Format" || echo "No changes to commit"
          git push